### ISSUE TITLE
Create a qemu image by docker container

### ISSUE THREAD

**Issue by TsuyoshiUshio** [kaz29/azutil#2]

**Comment by TsuyoshiUshio** [comment]
I'll develop a simple command which is upload VHD file which is created by docker.

**Comment by TsuyoshiUshio** [comment]
## TODO
- [] Design the use case of the command.
- [] Create a Storage Account and a Container
- [] Upload VHD file to the Container
